In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('tanks_data.csv')

y = data['Type']
X = data.drop(columns=['Type'])

n_features = X.shape[1]
n_rows = (n_features // 2) + (n_features % 2)
fig, axes = plt.subplots(n_rows, 2, figsize=(12, n_rows * 4))
axes = axes.ravel()

colors = {
    'Artillery': 'blue',
    'Heavy Tank': 'orange',
    'Light Tank': 'green',
    'Medium Tank': 'red',
    'Tank Destroyer': 'purple'
}

for i in range(n_features):
    _, bins = np.histogram(X.iloc[:, i], bins=50)
    
    for tank_type, color in colors.items():
        subset = X[y == tank_type].iloc[:, i]
        axes[i].hist(subset, bins=bins, color=color, alpha=0.5, label=tank_type)
    
    axes[i].set_title(X.columns[i])
    axes[i].set_yticks(())

axes[0].set_xlabel("Значение признака")
axes[0].set_ylabel("Частота")
axes[0].legend(colors.keys(), loc="best")

for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

fig.tight_layout()
plt.show()


In [ ]:
import pandas as pd
data = pd.read_csv('tanks_data.csv').drop(columns=['Type'])
corr = data.corr()
corr.style.background_gradient(cmap='coolwarm')

In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

data = pd.read_csv('tanks_data.csv')

X = data.drop(columns=['Type'])
y = data['Type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=15)

k = 2
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[22  1  0  0  0]
 [ 0 52  1  4  0]
 [ 0  0 28 16  1]
 [ 0  4  7 62  1]
 [ 0  4  0  6 41]]
                precision    recall  f1-score   support

     Artillery       1.00      0.96      0.98        23
    Heavy Tank       0.85      0.91      0.88        57
    Light Tank       0.78      0.62      0.69        45
   Medium Tank       0.70      0.84      0.77        74
Tank Destroyer       0.95      0.80      0.87        51

      accuracy                           0.82       250
     macro avg       0.86      0.83      0.84       250
  weighted avg       0.83      0.82      0.82       250



In [1]:
import pandas as pd
import KNN as knn
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

data = pd.read_csv('tanks_data.csv')

X = data.drop(columns=['Type'])
y = data['Type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=15)

model = knn.ClassifierKNN(metric='minkowski_1', window_size=8.5)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[23  0  0  0  0]
 [ 0 55  1  1  0]
 [ 0  0 40  4  1]
 [ 0  0  4 70  0]
 [ 0  2  0  3 46]]
                precision    recall  f1-score   support

     Artillery       1.00      1.00      1.00        23
    Heavy Tank       0.96      0.96      0.96        57
    Light Tank       0.89      0.89      0.89        45
   Medium Tank       0.90      0.95      0.92        74
Tank Destroyer       0.98      0.90      0.94        51

      accuracy                           0.94       250
     macro avg       0.95      0.94      0.94       250
  weighted avg       0.94      0.94      0.94       250



In [4]:
import KNN as knn
import pandas as pd
import multiprocessing
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

data = pd.read_csv('tanks_data.csv')

X = data.drop(columns=['Type'])
y = data['Type']

X_train, X_test, y_train, y_test = train_test_split(X, y)


# Параметры и их диапазоны
param_dist = {
    'n_neighbors': randint(1, 10),
    'metric': ['euclidean', 'cosine', 'minkowski_2', 'minkowski_1', 'minkowski_3'],
    'kernel': ['uniform', 'gaussian', 'epanechnikov', 'general'],
    'window_size': [None, 0.001, 0.1, 0.2, 0.5, 1, 2, 5, 8, 10, 15, 20],
    'a': randint(1, 4),
    'b': randint(1, 4)
}

knn_model = knn.ClassifierKNN()
n_jobs = multiprocessing.cpu_count() - 1

random_search = RandomizedSearchCV(knn_model, param_dist, cv=5, n_iter=200, n_jobs=n_jobs)
random_search.fit(X_train, y_train)

print("Лучшие параметры:", random_search.best_params_)
print("Лучшая точность:", random_search.best_score_)

#Лучшие параметры: {'a': 1, 'b': 2, 'kernel': 'gaussian', 'metric': 'minkowski_1', 'n_neighbors': 5, 'window_size': 15}
#Лучшая точность: 0.9383534675615213


Лучшие параметры: {'a': 1, 'b': 2, 'kernel': 'gaussian', 'metric': 'minkowski_1', 'n_neighbors': 5, 'window_size': 15}
Лучшая точность: 0.9383534675615213


C:\Users\valer\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_search.py:1103: UserWarning: One or more of the test scores are non-finite: [0.00936018        nan 0.7870604         nan 0.31195526        nan
        nan        nan        nan        nan 0.31061298        nan
        nan        nan 0.16055481        nan 0.70009843        nan
 0.73082774 0.73082774        nan        nan        nan 0.31061298
        nan 0.31061298 0.6935123         nan        nan        nan
 0.84598658        nan 0.70009843 0.77900671 0.73082774 0.68936913
 0.78035794 0.30927069        nan 0.93835347        nan 0.85941834
        nan 0.6935123  0.70009843 0.01606264        nan        nan
 0.30927069 0.48198658        nan        nan        nan        nan
        nan 0.6935123  0.16055481        nan 0.40038479 0.6935123
        nan 0.73082774 0.6935123         nan 0.70009843 0.70009843
 0.78303356        nan        nan 0.16055481        nan        nan
 0.70009843 0.30927069 