In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('tanks_data.csv')

y = data['Type']
X = data.drop(columns=['Type'])

n_features = X.shape[1]
n_rows = (n_features // 2) + (n_features % 2)
fig, axes = plt.subplots(n_rows, 2, figsize=(12, n_rows * 4))
axes = axes.ravel()

colors = {
    'Artillery': 'blue',
    'Heavy Tank': 'orange',
    'Light Tank': 'green',
    'Medium Tank': 'red',
    'Tank Destroyer': 'purple'
}

for i in range(n_features):
    _, bins = np.histogram(X.iloc[:, i], bins=50)
    
    for tank_type, color in colors.items():
        subset = X[y == tank_type].iloc[:, i]
        axes[i].hist(subset, bins=bins, color=color, alpha=0.5, label=tank_type)
    
    axes[i].set_title(X.columns[i])
    axes[i].set_yticks(())

axes[0].set_xlabel("Значение признака")
axes[0].set_ylabel("Частота")
axes[0].legend(colors.keys(), loc="best")

for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

fig.tight_layout()
plt.show()


KeyboardInterrupt: 

Error in callback <function _draw_all_if_interactive at 0x00000246B9C0F4C0> (for post_execute), with arguments args (),kwargs {}:


KeyboardInterrupt: 

Error in callback <function flush_figures at 0x00000246B9C5EB60> (for post_execute), with arguments args (),kwargs {}:


KeyboardInterrupt: 

In [36]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

data = pd.read_csv('tanks_data.csv')

X = data.drop(columns=['Type'])
y = data['Type']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

k = 5
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[14  0  0  0  0]
 [ 0 66  0  6  0]
 [ 0  0 39 10  1]
 [ 0  1  5 66  0]
 [ 0  2  1  3 36]]
                precision    recall  f1-score   support

     Artillery       1.00      1.00      1.00        14
    Heavy Tank       0.96      0.92      0.94        72
    Light Tank       0.87      0.78      0.82        50
   Medium Tank       0.78      0.92      0.84        72
Tank Destroyer       0.97      0.86      0.91        42

      accuracy                           0.88       250
     macro avg       0.91      0.89      0.90       250
  weighted avg       0.89      0.88      0.89       250



In [3]:
import pandas as pd
import KNN as knn
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Загружаем данные
data = pd.read_csv('tanks_data.csv')

# Разделяем данные на признаки и целевую переменную
X = data.drop(columns=['Type'])
y = data['Type']

# Разделяем данные на обучающую и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

# Инициализируем и обучаем модель
model = knn.ClassifierKNN(n_neighbors=5)
model.fit(X_train.values, y_train.values)  # Преобразуем в numpy массивы для sklearn

print(type(y_test))


y_pred = model.predict(X_test.values)
print(type(y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>
[[14  0  0  0  0]
 [ 0 66  0  6  0]
 [ 0  0 39  9  2]
 [ 0  1  4 67  0]
 [ 0  2  1  2 37]]
                precision    recall  f1-score   support

     Artillery       1.00      1.00      1.00        14
    Heavy Tank       0.96      0.92      0.94        72
    Light Tank       0.89      0.78      0.83        50
   Medium Tank       0.80      0.93      0.86        72
Tank Destroyer       0.95      0.88      0.91        42

      accuracy                           0.89       250
     macro avg       0.92      0.90      0.91       250
  weighted avg       0.90      0.89      0.89       250

